
project_id = "dnxyidnkmtrmkxucqrry"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://dnxyidnkmtrmkxucqrry.supabase.co", "https://game-master-scheduler-sync.lovable.app"]
jwt_expiry = 3600
disable_signup = false
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[auth.email.template.confirmation]
subject = "Confirmez votre inscription - Gestion Événements" 
content_path = "./supabase/templates/confirmation.html"

[auth.email.template.recovery]
subject = "Réinitialisation de votre mot de passe - Gestion Événements"
content_path = "./supabase/templates/recovery.html"

[auth.hook.send_email]
enabled = true
uri = "https://dnxyidnkmtrmkxucqrry.supabase.co/functions/v1/send-auth-emails"

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
file_size_limit = "50MiB"

[edge_runtime]
enabled = true
ip_version = "dual"

[functions.sync-make-calendar]
verify_jwt = false

[functions.make-webhook]
verify_jwt = false

[functions.auto-assign-gms]
verify_jwt = false

[functions.send-assignment-notification]
verify_jwt = false

[functions.send-auth-emails]
verify_jwt = false

[functions.gm-ical-feed]
verify_jwt = false

[functions.send-event-change-notification]
verify_jwt = false

[functions.send-admin-unassigned-notification]
verify_jwt = false

[functions.admin-delete-gm]
verify_jwt = false

[functions.admin-clean-duplicates]
verify_jwt = false

[functions.daily-gm-notifications]
verify_jwt = false

[functions.fix-monthly-reports]
verify_jwt = false

[functions.monthly-gm-emails]
verify_jwt = false

[functions.admin-ical-feed]
verify_jwt = false
